### ISSUE TITLE
 netlisting in Cadence virtuoso

### ISSUE THREAD

**Issue by 1864mp** [The-OpenROAD-Project/asap7_pdk_r1p7#1]
Hello I'm having an issue netlisting in Cadence virtuoso.

Cadence spectre will simulate hspice models yet it is not netlising using the supplied symbol even when a spectre view has been created.

Please could say how to overcome this? 

Looking at the CDF properties in the image below there does not seem enough parameters.

Thank you.

**Comment by maliberty** [comment]
We can't provide support for proprietary tools.
